import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { renderKnowledgeProductBody, validateExtractionBatch, verifyExtractionBatch } from "../src/extraction-result.ts";
import { captureKnowledge, type Qv5KnowledgeRevisionBatchEntry } from "../src/knowledge.ts";
import { renderKnowledge } from "../src/knowledge/codec.ts";
import { LedgerStore } from "../src/store.ts";

const hash = (value: string) => createHash("sha256").update(value).digest("hex");
const write = (path: string, value: string) => { mkdirSync(join(path, ".."), { recursive: true }); writeFileSync(path, value, { mode: 0o600 }); return path; };

export function createQv5Fixture(home: string, store: LedgerStore, title = "失败后的有界重试规则", options: { curatorSkills?: string[]; analystSkills?: string[]; analystScope?: "personal" | "work" } = {}) {
  const target = captureKnowledge(home, { title, scope: "work", type: "playbook", collection: "playbooks", sourceKind: "artifact", sourceRefs: ["src-old"], qualityVersion: 4, productType: "playbook", compilationRef: "old", factRefs: ["f1"], questionsAnswered: ["何时重试？"], admissionReason: "old", applicability: "old", boundary: "old", useWhen: "old", useInputs: ["a"], useOutputs: ["b"], useSteps: ["c"], useChecks: ["d"], useStopConditions: ["e"], confidenceBasis: ["old"], body: "old body" });
  const analystTask = store.createTask({ title: "analysis", goal: "analysis", acceptance: "analysis", scope: options.analystScope ?? "work" }); store.transitionTask(analystTask.id, "active"); const analyst = store.createRun(analystTask.id, "ikb-analyst", options.analystSkills ?? ["ikb-conversation-analysis"]);
  const curatorTask = store.createTask({ title: "curation", goal: "curation", acceptance: "curation", scope: "work" }); store.transitionTask(curatorTask.id, "active"); const curator = store.createRun(curatorTask.id, "ikb-curator", options.curatorSkills ?? ["ikb-knowledge-curator"]);
  const root = join(home, "fixtures", target.id); const text = "条件变化且副作用可控时，才允许一次有界重试。"; const sourcePath = write(join(root, "source.md"), `${text}\n`);
  const manifest = { schema: "ikb-knowledge-extraction-benchmark.v3", benchmark_id: "qv5", cases: [{ case_id: "case", category: "playbook", title, input_fingerprint: "a".repeat(64), extraction_modes: ["playbook"], source_ids: ["src"], source_snapshots: [{ source_id: "src", path: sourcePath, content_sha256: hash(`${text}\n`) }], consumer_tasks: ["recover"], obligations: [{ obligation_id: "o", description: "何时重试", importance: "core", required_product_types: ["playbook"] }], source_units: [{ unit_id: "u", source_id: "src", unit_kind: "paragraph", locator: "1", content: text, content_sha256: hash(text), importance: "core" }], reference_facts: [{ reference_fact_id: "rf", statement: text, importance: "core", source_unit_refs: ["u"], question_refs: ["q"] }], questions: [{ question_id: "q", text: "何时重试？", importance: "core", required_product_types: ["playbook"] }], existing_knowledge: [{ knowledge_id: target.id, canonical_key: "work:qv5:playbook" }] }] };
  const result = { schema: "ikb-knowledge-compilation-result.v3", benchmark_id: "qv5", case_id: "case", input_fingerprint: "a".repeat(64), extraction_modes: ["playbook"], disposition: "admit", disposition_reason: "rule", evidence_units: [{ evidence_id: "e", source_id: "src", record_id: "src:1", locator: "1", excerpt: text, excerpt_sha256: hash(text), attribution_role: "author", actor: "a", occurred_at: "2026-08-01T00:00:00Z", source_unit_refs: ["u"] }], facts: [{ fact_id: "f1", fact_kind: "procedure_rule", statement: text, evidence_ids: ["e"], reference_fact_refs: ["rf"], derivation: "direct", temporal_state: "current", importance: "core" }], claims: [{ claim_id: "c", text, claim_kind: "synthesis", fact_refs: ["f1"], counterevidence_fact_refs: [], reasoning: "direct", temporal_state: "current", support_status: "supported" }], coverage: [{ obligation_id: "o", disposition: "covered", fact_refs: ["f1"], reason: "covered" }], source_unit_dispositions: [{ unit_id: "u", disposition: "extracted", evidence_ids: ["e"], fact_refs: ["f1"], reason: "kept" }], reference_fact_dispositions: [{ reference_fact_id: "rf", disposition: "preserved", fact_refs: ["f1"], reason: "kept" }], products: [{ product_id: "p", product_type: "playbook", title, canonical_key: "work:qv5:playbook", operation: "revise", primary_knowledge_id: target.id, unique_value: "bounded", fact_refs: ["f1"], claim_refs: ["c"], question_refs: ["q"], consumer_tasks: ["recover"], questions_answered: ["何时重试？"], boundaries: ["side effects"], verification_plan: ["replay"], procedure: { preconditions: ["changed"], inputs: ["evidence"], steps: ["retry once"], checks: ["safe"], branches: ["stop"], rollback: ["stop"], stop_conditions: ["same failure"] } }], question_results: [{ question_id: "q", disposition: "answered", fact_refs: ["f1"], product_refs: ["p"], reason: "answer" }], unknowns: [], next_triggers: ["change"] };
  const inspection = validateExtractionBatch(manifest, [result]); if (!inspection.valid) throw new Error(JSON.stringify(inspection.issues));
  const manifestArtifact = store.createArtifact({ runId: analyst.id, kind: "knowledge-extraction-manifest", label: "manifest", path: write(join(root, "manifest.json"), JSON.stringify(manifest)) });
  const compilationArtifact = store.createArtifact({ runId: analyst.id, kind: "knowledge-extraction-result", label: "result", path: write(join(root, "result.json"), JSON.stringify({ results: [result] })) });
  const fidelityArtifact = store.createArtifact({ runId: analyst.id, kind: "knowledge-extraction-fidelity", label: "fidelity", path: write(join(root, "fidelity.json"), JSON.stringify(verifyExtractionBatch(manifest, [result]))) });
  const body = renderKnowledgeProductBody(result, "case", "p");
  const replacementText = renderKnowledge({ ...target, qualityVersion: 5, canonicalKey: "work:qv5:playbook", compilationSchema: "ikb-knowledge-compilation-result.v3", compilationCaseId: "case", compilationProductId: "p", extractionManifestRef: manifestArtifact.id, compilationRef: compilationArtifact.id, informationLossRef: fidelityArtifact.id, factRefs: ["f1"], questionsAnswered: ["何时重试？"], body });
  const replacementArtifact = store.createArtifact({ runId: curator.id, kind: "knowledge-qv5-replacement-draft", label: "replacement", path: write(join(root, "replacement.md"), replacementText) });
  const validationArtifact = store.createArtifact({ runId: curator.id, kind: "knowledge-qv5-validation", label: "validation", path: write(join(root, "validation.json"), JSON.stringify({ knowledgeId: target.id, bodyExact: true, renderedHash: hash(replacementText) })) });
  const entry: Qv5KnowledgeRevisionBatchEntry = { knowledgeId: target.id, expectedRevision: target.revision, expectedKnowledgeHash: hash(readFileSync(target.path, "utf8")), replacementArtifactId: replacementArtifact.id, validationArtifactId: validationArtifact.id, manifestArtifactId: manifestArtifact.id, compilationArtifactId: compilationArtifact.id, fidelityArtifactId: fidelityArtifact.id };
  return { target, entry, input: { knowledgeId: target.id, replacementArtifactId: replacementArtifact.id, validationArtifactId: validationArtifact.id, manifestArtifactId: manifestArtifact.id, compilationArtifactId: compilationArtifact.id, fidelityArtifactId: fidelityArtifact.id }, paths: { fidelity: fidelityArtifact.path, replacement: replacementArtifact.path }, analyst, curator };
}
