import type {
  DailyCopilotCategory,
  DailyCopilotMigrationManifest,
  DailyCopilotPublicMapping,
  PublicationBundle,
  PublicationManifest,
} from "../contracts.ts";

export interface DailyCopilotOutput {
  manifest: PublicationManifest;
  files: Array<{ path: string; content: string }>;
}

export function buildDailyCopilotOutput(
  bundle: PublicationBundle,
  bundleHash: string,
  migration: DailyCopilotMigrationManifest,
  mappings: DailyCopilotPublicMapping[],
  migrationHash: string,
): DailyCopilotOutput {
  const entriesByPublicId = new Map(bundle.entries.map((entry) => [entry.public_id, entry]));
  const rows = mappings
    .slice()
    .sort((left, right) => left.legacy_id - right.legacy_id)
    .map((mapping) => {
      const entry = entriesByPublicId.get(mapping.public_id);
      if (!entry) throw new Error(`Daily Copilot mapping references an unknown public entry: ${mapping.public_id}`);
      return {
        id: mapping.legacy_id,
        publicId: entry.public_id,
        t: mapping.title ?? entry.title,
        d: entry.summary,
        cat: mapping.category ?? entry.category,
        tags: entry.tags,
        content: renderMiniProgramHtml(entry.content_markdown),
        contentHash: entry.content_hash,
        attachments: [],
      };
    });
  const categories = orderedCategories(rows.map((row) => row.cat), migration);
  const publishedIds = new Set(rows.map((row) => row.id));
  const omittedIds = migration.expected_legacy_ids.filter((id) => !publishedIds.has(id));
  const mappingByLegacyId = new Map(mappings.map((entry) => [entry.legacy_id, entry]));
  const manifest: PublicationManifest = {
    schema_version: "ikb-daily-copilot-manifest.v1",
    channel: "daily-copilot",
    bundle_hash: bundleHash,
    migration_hash: migrationHash,
    expected_legacy_ids: [...migration.expected_legacy_ids],
    omitted_legacy_ids: omittedIds,
    categories,
    entries: rows.map((row) => {
      const mapping = mappingByLegacyId.get(row.id)!;
      return {
        legacy_id: row.id,
        public_id: row.publicId,
        title: row.t,
        category: row.cat,
        tags: row.tags,
        path: "experience-data.js",
        content_hash: row.contentHash,
        attachment_disposition: mapping.attachment_disposition,
      };
    }),
  };
  return {
    manifest,
    files: [
      {
        path: "experience-data.js",
        content: renderCommonJs(
          "GENERATED by IKB Daily Copilot Adapter. Edit Knowledge or the private migration manifest, then rebuild.",
          rows,
        ),
      },
      {
        path: "experience-categories.js",
        content: renderCommonJs(
          "GENERATED by IKB Daily Copilot Adapter. Category order and icons come from the migration contract.",
          categories,
        ),
      },
    ],
  };
}

function orderedCategories(categoryNames: string[], migration: DailyCopilotMigrationManifest): DailyCopilotCategory[] {
  const used = new Set(categoryNames);
  const declared = migration.category_order.filter((name) => used.has(name));
  const undeclared = [...used].filter((name) => !migration.category_order.includes(name)).sort();
  return [...declared, ...undeclared].map((name) => ({
    name,
    icon: migration.category_icons[name] ?? "📝",
  }));
}

function renderCommonJs(comment: string, value: unknown): string {
  return `/**\n * ${comment}\n */\nmodule.exports = ${JSON.stringify(value, null, 2)}\n`;
}

function renderMiniProgramHtml(markdown: string): string {
  const lines = markdown.trim().replace(/\r\n/g, "\n").split("\n");
  const blocks: string[] = [];
  let paragraph: string[] = [];
  let listType: "ul" | "ol" | null = null;
  let listItems: string[] = [];
  let code: string[] | null = null;

  const flushParagraph = () => {
    if (paragraph.length === 0) return;
    blocks.push(`<p>${inlineMarkdown(paragraph.join(" "))}</p>`);
    paragraph = [];
  };
  const flushList = () => {
    if (!listType || listItems.length === 0) return;
    blocks.push(`<${listType}>${listItems.map((item) => `<li>${inlineMarkdown(item)}</li>`).join("")}</${listType}>`);
    listType = null;
    listItems = [];
  };
  const flushCode = () => {
    if (!code) return;
    blocks.push(`<pre><code>${escapeHtml(code.join("\n"))}</code></pre>`);
    code = null;
  };

  for (const line of lines) {
    if (/^```/.test(line.trim())) {
      flushParagraph();
      flushList();
      if (code) flushCode();
      else code = [];
      continue;
    }
    if (code) {
      code.push(line);
      continue;
    }
    const heading = /^(#{1,6})\s+(.+)$/.exec(line);
    if (heading) {
      flushParagraph();
      flushList();
      blocks.push(`<h4>${inlineMarkdown(heading[2])}</h4>`);
      continue;
    }
    const unordered = /^\s*[-*]\s+(.+)$/.exec(line);
    const ordered = /^\s*\d+\.\s+(.+)$/.exec(line);
    if (unordered || ordered) {
      flushParagraph();
      const nextType = unordered ? "ul" : "ol";
      if (listType && listType !== nextType) flushList();
      listType = nextType;
      listItems.push((unordered ?? ordered)![1]);
      continue;
    }
    if (!line.trim()) {
      flushParagraph();
      flushList();
      continue;
    }
    paragraph.push(line.trim());
  }
  flushParagraph();
  flushList();
  flushCode();
  return blocks.join("");
}

function inlineMarkdown(value: string): string {
  return escapeHtml(value)
    .replace(/\*\*([^*]+)\*\*/g, "<b>$1</b>")
    .replace(/`([^`]+)`/g, "<code>$1</code>");
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
