import { existsSync, readdirSync, statSync } from "node:fs";
import { join, relative } from "node:path";
import type { KnowledgeRecord } from "../types.ts";
import { resolveVault } from "../layout.ts";
import { knowledgeScopes, resolveKnowledgeDirectory } from "./catalog.ts";
import { KNOWLEDGE_DIRECTORIES, type KnowledgeDirectory, type KnowledgeViewSummary } from "./contracts.ts";
import { today } from "./codec.ts";
import { listKnowledge } from "./records.ts";
import {
  compareKnowledge,
  ensurePrivateDirectory,
  GOVERNANCE_DIRECTORIES,
  governanceRoot,
  LEGACY_KNOWLEDGE_DIRECTORY,
  migrationJournalRoot,
  writeGeneratedFile,
} from "./storage.ts";

export function initializeKnowledgeLayout(home: string, scope?: string): KnowledgeViewSummary[] {
  return rebuildKnowledgeViews(home, scope);
}

export function rebuildKnowledgeViews(home: string, scope?: string): KnowledgeViewSummary[] {
  return knowledgeScopes(scope).map((currentScope) => {
    const vault = resolveVault(home, currentScope);
    const governance = governanceRoot(home, currentScope);
    ensureKnowledgeLayout(home, currentScope);
    const records = listKnowledge(home, currentScope);
    const byDirectory = new Map<KnowledgeDirectory, KnowledgeRecord[]>(KNOWLEDGE_DIRECTORIES.map((directory) => [directory, []]));
    for (const record of records) byDirectory.get(resolveKnowledgeDirectory(record.type, record.collection))!.push(record);
    for (const directory of KNOWLEDGE_DIRECTORIES) {
      const directoryRecords = byDirectory.get(directory)!.sort(compareKnowledge);
      writeGeneratedFile(join(vault, directory, "index.md"), renderDirectoryIndex(vault, currentScope, directory, directoryRecords));
    }
    const summary = summarizeKnowledge(currentScope, vault, governance, records);
    writeGeneratedFile(summary.indexPath, renderVaultIndex(summary, byDirectory));
    writeGeneratedFile(summary.statusPath, renderGovernanceStatus(summary, records));
    return summary;
  });
}

export function ensureKnowledgeLayout(home: string, scope: string): void {
  const vault = resolveVault(home, scope);
  const governance = governanceRoot(home, scope);
  ensurePrivateDirectory(vault);
  for (const directory of KNOWLEDGE_DIRECTORIES) ensurePrivateDirectory(join(vault, directory));
  ensurePrivateDirectory(governance);
  ensurePrivateDirectory(migrationJournalRoot(home));
  for (const directory of GOVERNANCE_DIRECTORIES) ensurePrivateDirectory(join(governance, directory));
}

function summarizeKnowledge(scope: string, vault: string, governance: string, records: KnowledgeRecord[]): KnowledgeViewSummary {
  const dueForReview = records.filter((record) => record.status === "draft" || record.reviewAfter <= today()).length;
  return {
    scope,
    vault,
    indexPath: join(vault, "index.md"),
    statusPath: join(governance, "status.md"),
    total: records.length,
    draft: records.filter((record) => record.status === "draft").length,
    verified: records.filter((record) => record.status === "verified").length,
    retired: records.filter((record) => record.status === "retired").length,
    dueForReview,
    legacy: records.filter((record) => relative(vault, record.path).split(/[\\/]/)[0] === LEGACY_KNOWLEDGE_DIRECTORY).length,
  };
}

function renderVaultIndex(summary: KnowledgeViewSummary, byDirectory: Map<KnowledgeDirectory, KnowledgeRecord[]>): string {
  const title = summary.scope === "work" ? "Work Knowledge" : "Personal Knowledge";
  return [
    `# ${title}`, "", "> Generated by ikb. Edit knowledge notes, not this index.", "",
    "## Browse", "", "| Collection | Entries |", "|---|---:|",
    ...KNOWLEDGE_DIRECTORIES.map((directory) => `| [[${directory}/index|${collectionTitle(directory)}]] | ${byDirectory.get(directory)!.length} |`),
    "", "## Status", "", `- Total: ${summary.total}`, `- Verified: ${summary.verified}`,
    `- Draft: ${summary.draft}`, `- Retired: ${summary.retired}`, `- Due for review: ${summary.dueForReview}`,
    `- Legacy entries: ${summary.legacy}`, "",
  ].join("\n");
}

function renderDirectoryIndex(vault: string, scope: string, directory: KnowledgeDirectory, records: KnowledgeRecord[]): string {
  const renderRows = (items: KnowledgeRecord[]) => items.map((record) => {
    const target = relative(vault, record.path).replaceAll("\\", "/").replace(/\.md$/i, "");
    return `| [[${target}|${escapeObsidianAlias(record.title)}]] | ${escapeTableCell(record.type)} | ${record.status} | ${record.reviewAfter} |`;
  });
  const current = records.filter((record) => record.status !== "retired");
  const archived = records.filter((record) => record.status === "retired");
  const personDossiers = directory === "people" ? listPersonDossiers(vault) : [];
  return [
    `# ${collectionTitle(directory)}`, "", `> Generated by ikb for the ${scope} vault. Edit knowledge notes, not this index.`, "",
    "## Current knowledge", "",
    ...(current.length > 0 ? ["| Knowledge | Type | Status | Review after |", "|---|---|---|---|", ...renderRows(current)] : ["_No current knowledge yet._"]),
    ...(archived.length > 0 ? ["", "## Archived knowledge (audit only)", "", "> Retired notes are preserved for traceability and are excluded from default retrieval.", "", "| Knowledge | Type | Status | Review after |", "|---|---|---|---|", ...renderRows(archived)] : []),
    ...(personDossiers.length > 0 ? ["", "## Person views", "", ...personDossiers.map((id) => `- [[people/${id}/index|${id}]]`)] : []),
    "",
  ].join("\n");
}

function listPersonDossiers(vault: string): string[] {
  const root = join(vault, "people");
  if (!existsSync(root) || !statSync(root).isDirectory()) return [];
  return readdirSync(root, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && !entry.isSymbolicLink() && existsSync(join(root, entry.name, "index.md")))
    .map((entry) => entry.name)
    .sort((left, right) => left.localeCompare(right));
}

function renderGovernanceStatus(summary: KnowledgeViewSummary, records: KnowledgeRecord[]): string {
  const typeCounts = [...new Set(records.map((record) => record.type))].sort().map((type) => {
    const typed = records.filter((record) => record.type === type);
    return `| ${escapeTableCell(type)} | ${typed.length} | ${typed.filter((record) => record.status === "verified").length} | ${typed.filter((record) => record.status === "draft").length} |`;
  });
  return [
    `# ${summary.scope === "work" ? "Work" : "Personal"} knowledge status`, "", "> Generated by ikb from the Markdown knowledge files.", "",
    `- Total: ${summary.total}`, `- Verified: ${summary.verified}`, `- Draft: ${summary.draft}`, `- Retired: ${summary.retired}`,
    `- Due for review: ${summary.dueForReview}`, `- Legacy entries: ${summary.legacy}`, "", "## By type", "",
    ...(typeCounts.length > 0 ? ["| Type | Total | Verified | Draft |", "|---|---:|---:|---:|", ...typeCounts] : ["_No knowledge yet._"]), "",
  ].join("\n");
}

function collectionTitle(directory: KnowledgeDirectory): string {
  return directory[0].toUpperCase() + directory.slice(1);
}

function escapeTableCell(value: string): string {
  return value.replaceAll("|", "/").replaceAll("\n", " ").trim();
}

function escapeObsidianAlias(value: string): string {
  return escapeTableCell(value).replaceAll("[", "").replaceAll("]", "");
}
